/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppEmployeesRouteImport } from './routes/app.employees'
import { Route as AppExpensesRouteImport } from './routes/app.expenses'
import { Route as AppInvoicesRouteImport } from './routes/app.invoices'
import { Route as AppProcurementRouteImport } from './routes/app.procurement'
import { Route as AppRecordsRouteImport } from './routes/app.records'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppRevenueRouteImport } from './routes/app.revenue'
import { Route as AppScannerRouteImport } from './routes/app.scanner'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppVendorReconciliationRouteImport } from './routes/app.vendor-reconciliation'
import { Route as AppVendorsRouteImport } from './routes/app.vendors'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppEmployeesRoute = AppEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppExpensesRoute = AppExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppProcurementRoute = AppProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => AppRoute,
} as any)
const AppRecordsRoute = AppRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRevenueRoute = AppRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => AppRoute,
} as any)
const AppScannerRoute = AppScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorReconciliationRoute = AppVendorReconciliationRouteImport.update({
  id: '/vendor-reconciliation',
  path: '/vendor-reconciliation',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorsRoute = AppVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/procurement': typeof AppProcurementRoute
  '/app/records': typeof AppRecordsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/revenue': typeof AppRevenueRoute
  '/app/scanner': typeof AppScannerRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vendor-reconciliation': typeof AppVendorReconciliationRoute
  '/app/vendors': typeof AppVendorsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/procurement': typeof AppProcurementRoute
  '/app/records': typeof AppRecordsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/revenue': typeof AppRevenueRoute
  '/app/scanner': typeof AppScannerRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vendor-reconciliation': typeof AppVendorReconciliationRoute
  '/app/vendors': typeof AppVendorsRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/employees': typeof AppEmployeesRoute
  '/app/expenses': typeof AppExpensesRoute
  '/app/invoices': typeof AppInvoicesRoute
  '/app/procurement': typeof AppProcurementRoute
  '/app/records': typeof AppRecordsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/revenue': typeof AppRevenueRoute
  '/app/scanner': typeof AppScannerRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/vendor-reconciliation': typeof AppVendorReconciliationRoute
  '/app/vendors': typeof AppVendorsRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/analytics'
    | '/app/assistant'
    | '/app/documents'
    | '/app/employees'
    | '/app/expenses'
    | '/app/invoices'
    | '/app/procurement'
    | '/app/records'
    | '/app/reports'
    | '/app/revenue'
    | '/app/scanner'
    | '/app/settings'
    | '/app/vendor-reconciliation'
    | '/app/vendors'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/analytics'
    | '/app/assistant'
    | '/app/documents'
    | '/app/employees'
    | '/app/expenses'
    | '/app/invoices'
    | '/app/procurement'
    | '/app/records'
    | '/app/reports'
    | '/app/revenue'
    | '/app/scanner'
    | '/app/settings'
    | '/app/vendor-reconciliation'
    | '/app/vendors'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/analytics'
    | '/app/assistant'
    | '/app/documents'
    | '/app/employees'
    | '/app/expenses'
    | '/app/invoices'
    | '/app/procurement'
    | '/app/records'
    | '/app/reports'
    | '/app/revenue'
    | '/app/scanner'
    | '/app/settings'
    | '/app/vendor-reconciliation'
    | '/app/vendors'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/employees': {
      id: '/app/employees'
      path: '/employees'
      fullPath: '/app/employees'
      preLoaderRoute: typeof AppEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/expenses': {
      id: '/app/expenses'
      path: '/expenses'
      fullPath: '/app/expenses'
      preLoaderRoute: typeof AppExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/invoices': {
      id: '/app/invoices'
      path: '/invoices'
      fullPath: '/app/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/procurement': {
      id: '/app/procurement'
      path: '/procurement'
      fullPath: '/app/procurement'
      preLoaderRoute: typeof AppProcurementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/records': {
      id: '/app/records'
      path: '/records'
      fullPath: '/app/records'
      preLoaderRoute: typeof AppRecordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/revenue': {
      id: '/app/revenue'
      path: '/revenue'
      fullPath: '/app/revenue'
      preLoaderRoute: typeof AppRevenueRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/scanner': {
      id: '/app/scanner'
      path: '/scanner'
      fullPath: '/app/scanner'
      preLoaderRoute: typeof AppScannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendor-reconciliation': {
      id: '/app/vendor-reconciliation'
      path: '/vendor-reconciliation'
      fullPath: '/app/vendor-reconciliation'
      preLoaderRoute: typeof AppVendorReconciliationRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/vendors': {
      id: '/app/vendors'
      path: '/vendors'
      fullPath: '/app/vendors'
      preLoaderRoute: typeof AppVendorsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppEmployeesRoute: typeof AppEmployeesRoute
  AppExpensesRoute: typeof AppExpensesRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppProcurementRoute: typeof AppProcurementRoute
  AppRecordsRoute: typeof AppRecordsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppRevenueRoute: typeof AppRevenueRoute
  AppScannerRoute: typeof AppScannerRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVendorReconciliationRoute: typeof AppVendorReconciliationRoute
  AppVendorsRoute: typeof AppVendorsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppEmployeesRoute: AppEmployeesRoute,
  AppExpensesRoute: AppExpensesRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppProcurementRoute: AppProcurementRoute,
  AppRecordsRoute: AppRecordsRoute,
  AppReportsRoute: AppReportsRoute,
  AppRevenueRoute: AppRevenueRoute,
  AppScannerRoute: AppScannerRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVendorReconciliationRoute: AppVendorReconciliationRoute,
  AppVendorsRoute: AppVendorsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
